package rpm

type Tag int32

func (t Tag) String() string {
	v, ok := tags[t]
	if !ok {
		return "unknown"
	}
	return v
}

const (
	TagNAME Tag = iota + 1000
	TagVERSION
	TagRELEASE
	TagEPOCH
	TagSUMMARY
	TagDESCRIPTION
	TagBUILDTIME
	TagBUILDHOST
	TagINSTALLTIME
	TagSIZE
	TagDISTRIBUTION
	TagVENDOR
	TagGIF
	TagXPM
	TagLICENSE
	TagPACKAGER
	TagGROUP
	TagCHANGELOG
	TagSOURCE
	TagPATCH
	TagURL
	TagOS
	TagARCH
	TagPREIN
	TagPOSTIN
	TagPREUN
	TagPOSTUN
	TagOLDFILENAMES
	TagFILESIZES
	TagFILESTATES
	TagFILEMODES
	TagFILEUIDS
	TagFILEGIDS
	TagFILERDEVS
	TagFILEMTIMES
	TagFILEDIGESTS
	TagFILELINKTOS
	TagFILEFLAGS
	TagROOT
	TagFILEUSERNAME
	TagFILEGROUPNAME
	TagEXCLUDE
	TagEXCLUSIVE
	TagICON
	TagSOURCERPM
	TagFILEVERIFYFLAGS
	TagARCHIVESIZE
	TagPROVIDENAME
	TagREQUIREFLAGS
	TagREQUIRENAME
	TagREQUIREVERSION
	TagNOSOURCE
	TagNOPATCH
	TagCONFLICTFLAGS
	TagCONFLICTNAME
	TagCONFLICTVERSION
	TagDEFAULTPREFIX
	TagBUILDROOT
	TagINSTALLPREFIX
	TagEXCLUDEARCH
	TagEXCLUDEOS
	TagEXCLUSIVEARCH
	TagEXCLUSIVEOS
	TagAUTOREQPROV
	TagRPMVERSION
	TagTRIGGERSCRIPTS
	TagTRIGGERNAME
	TagTRIGGERVERSION
	TagTRIGGERFLAGS
	TagTRIGGERINDEX
	TagVERIFYSCRIPT
	TagCHANGELOGTIME
	TagCHANGELOGNAME
	TagCHANGELOGTEXT
	TagBROKENMD5
	TagPREREQ
	TagPREINPROG
	TagPOSTINPROG
	TagPREUNPROG
	TagPOSTUNPROG
	TagBUILDARCHS
	TagOBSOLETENAME
	TagVERIFYSCRIPTPROG
	TagTRIGGERSCRIPTPROG
	TagDOCDIR
	TagCOOKIE
	TagFILEDEVICES
	TagFILEINODES
	TagFILELANGS
	TagPREFIXES
	TagINSTPREFIXES
	TagTRIGGERIN
	TagTRIGGERUN
	TagTRIGGERPOSTUN
	TagAUTOREQ
	TagAUTOPROV
	TagCAPABILITY
	TagSOURCEPACKAGE
	TagOLDORIGFILENAMES
	TagBUILDPREREQ
	TagBUILDREQUIRES
	TagBUILDCONFLICTS
	TagBUILDMACROS
	TagPROVIDEFLAGS
	TagPROVIDEVERSION
	TagOBSOLETEFLAGS
	TagOBSOLETEVERSION
	TagDIRINDEXES
	TagBASENAMES
	TagDIRNAMES
	TagORIGDIRINDEXES
	TagORIGBASENAMES
	TagORIGDIRNAMES
	TagOPTFLAGS
	TagDISTURL
	TagPAYLOADFORMAT
	TagPAYLOADCOMPRESSOR
	TagPAYLOADFLAGS
	TagINSTALLCOLOR
	TagINSTALLTID
	TagREMOVETID
	TagSHA1RHN
	TagRHNPLATFORM
	TagPLATFORM
	TagPATCHESNAME
	TagPATCHESFLAGS
	TagPATCHESVERSION
	TagCACHECTIME
	TagCACHEPKGPATH
	TagCACHEPKGSIZE
	TagCACHEPKGMTIME
	TagFILECOLORS
	TagFILECLASS
	TagCLASSDICT
	TagFILEDEPENDSX
	TagFILEDEPENDSN
	TagDEPENDSDICT
	TagSOURCEPKGID
	TagFILECONTEXTS
	TagFSCONTEXTS
	TagRECONTEXTS
	TagPOLICIES
	TagPRETRANS
	TagPOSTTRANS
	TagPRETRANSPROG
	TagPOSTTRANSPROG
	TagDISTTAG
	TagOLDSUGGESTSNAME
	TagOLDSUGGESTSVERSION
	TagOLDSUGGESTSFLAGS
	TagOLDENHANCESNAME
	TagOLDENHANCESVERSION
	TagOLDENHANCESFLAGS
	TagPRIORITY
	TagCVSID
	TagBLINKPKGID
	TagBLINKHDRID
	TagBLINKNEVRA
	TagFLINKPKGID
	TagFLINKHDRID
	TagFLINKNEVRA
	TagPACKAGEORIGIN
	TagTRIGGERPREIN
	TagBUILDSUGGESTS
	TagBUILDENHANCES
	TagSCRIPTSTATES
	TagSCRIPTMETRICS
	TagBUILDCPUCLOCK
	TagFILEDIGESTALGOS
	TagVARIANTS
	TagXMAJOR
	TagXMINOR
	TagREPOTAG
	TagKEYWORDS
	TagBUILDPLATFORMS
	TagPACKAGECOLOR
	TagPACKAGEPREFCOLOR
	TagXATTRSDICT
	TagFILEXATTRSX
	TagDEPATTRSDICT
	TagCONFLICTATTRSX
	TagOBSOLETEATTRSX
	TagPROVIDEATTRSX
	TagREQUIREATTRSX
	TagBUILDPROVIDES
	TagBUILDOBSOLETES
	TagDBINSTANCE
	TagNVRA
	TagFILENAMES Tag = iota + 5000
	TagFILEPROVIDE
	TagFILEREQUIRE
	TagFSNAMES
	TagFSSIZES
	TagTRIGGERCONDS
	TagTRIGGERTYPE
	TagORIGFILENAMES
	TagLONGFILESIZES
	TagLONGSIZE
	TagFILECAPS
	TagFILEDIGESTALGO
	TagBUGURL
	TagEVR
	TagNVR
	TagNEVR
	TagNEVRA
	TagHEADERCOLOR
	TagVERBOSE
	TagEPOCHNUM
	TagPREINFLAGS
	TagPOSTINFLAGS
	TagPREUNFLAGS
	TagPOSTUNFLAGS
	TagPRETRANSFLAGS
	TagPOSTTRANSFLAGS
	TagVERIFYSCRIPTFLAGS
	TagTRIGGERSCRIPTFLAGS
	TagCOLLECTIONS
	TagPOLICYNAMES
	TagPOLICYTYPES
	TagPOLICYTYPESINDEXES
	TagPOLICYFLAGS
	TagVCS
	TagORDERNAME
	TagORDERVERSION
	TagORDERFLAGS
	TagMSSFMANIFEST
	TagMSSFDOMAIN
	TagINSTFILENAMES
	TagREQUIRENEVRS
	TagPROVIDENEVRS
	TagOBSOLETENEVRS
	TagCONFLICTNEVRS
	TagFILENLINKS
	TagRECOMMENDNAME
	TagRECOMMENDVERSION
	TagRECOMMENDFLAGS
	TagSUGGESTNAME
	TagSUGGESTVERSION
	TagSUGGESTFLAGS
	TagSUPPLEMENTNAME
	TagSUPPLEMENTVERSION
	TagSUPPLEMENTFLAGS
	TagENHANCENAME
	TagENHANCEVERSION
	TagENHANCEFLAGS
	TagRECOMMENDNEVRS
	TagSUGGESTNEVRS
	TagSUPPLEMENTNEVRS
	TagENHANCENEVRS
)

var tags = map[Tag]string{
	TagNAME:               "NAME",
	TagVERSION:            "VERSION",
	TagRELEASE:            "RELEASE",
	TagEPOCH:              "EPOCH",
	TagSUMMARY:            "SUMMARY",
	TagDESCRIPTION:        "DESCRIPTION",
	TagBUILDTIME:          "BUILDTIME",
	TagBUILDHOST:          "BUILDHOST",
	TagINSTALLTIME:        "INSTALLTIME",
	TagSIZE:               "SIZE",
	TagDISTRIBUTION:       "DISTRIBUTION",
	TagVENDOR:             "VENDOR",
	TagGIF:                "GIF",
	TagXPM:                "XPM",
	TagLICENSE:            "LICENSE",
	TagPACKAGER:           "PACKAGER",
	TagGROUP:              "GROUP",
	TagCHANGELOG:          "CHANGELOG",
	TagSOURCE:             "SOURCE",
	TagPATCH:              "PATCH",
	TagURL:                "URL",
	TagOS:                 "OS",
	TagARCH:               "ARCH",
	TagPREIN:              "PREIN",
	TagPOSTIN:             "POSTIN",
	TagPREUN:              "PREUN",
	TagPOSTUN:             "POSTUN",
	TagOLDFILENAMES:       "OLDFILENAMES",
	TagFILESIZES:          "FILESIZES",
	TagFILESTATES:         "FILESTATES",
	TagFILEMODES:          "FILEMODES",
	TagFILEUIDS:           "FILEUIDS",
	TagFILEGIDS:           "FILEGIDS",
	TagFILERDEVS:          "FILERDEVS",
	TagFILEMTIMES:         "FILEMTIMES",
	TagFILEDIGESTS:        "FILEDIGESTS",
	TagFILELINKTOS:        "FILELINKTOS",
	TagFILEFLAGS:          "FILEFLAGS",
	TagROOT:               "ROOT",
	TagFILEUSERNAME:       "FILEUSERNAME",
	TagFILEGROUPNAME:      "FILEGROUPNAME",
	TagEXCLUDE:            "EXCLUDE",
	TagEXCLUSIVE:          "EXCLUSIVE",
	TagICON:               "ICON",
	TagSOURCERPM:          "SOURCERPM",
	TagFILEVERIFYFLAGS:    "FILEVERIFYFLAGS",
	TagARCHIVESIZE:        "ARCHIVESIZE",
	TagPROVIDENAME:        "PROVIDENAME",
	TagREQUIREFLAGS:       "REQUIREFLAGS",
	TagREQUIRENAME:        "REQUIRENAME",
	TagREQUIREVERSION:     "REQUIREVERSION",
	TagNOSOURCE:           "NOSOURCE",
	TagNOPATCH:            "NOPATCH",
	TagCONFLICTFLAGS:      "CONFLICTFLAGS",
	TagCONFLICTNAME:       "CONFLICTNAME",
	TagCONFLICTVERSION:    "CONFLICTVERSION",
	TagDEFAULTPREFIX:      "DEFAULTPREFIX",
	TagBUILDROOT:          "BUILDROOT",
	TagINSTALLPREFIX:      "INSTALLPREFIX",
	TagEXCLUDEARCH:        "EXCLUDEARCH",
	TagEXCLUDEOS:          "EXCLUDEOS",
	TagEXCLUSIVEARCH:      "EXCLUSIVEARCH",
	TagEXCLUSIVEOS:        "EXCLUSIVEOS",
	TagAUTOREQPROV:        "AUTOREQPROV",
	TagRPMVERSION:         "RPMVERSION",
	TagTRIGGERSCRIPTS:     "TRIGGERSCRIPTS",
	TagTRIGGERNAME:        "TRIGGERNAME",
	TagTRIGGERVERSION:     "TRIGGERVERSION",
	TagTRIGGERFLAGS:       "TRIGGERFLAGS",
	TagTRIGGERINDEX:       "TRIGGERINDEX",
	TagVERIFYSCRIPT:       "VERIFYSCRIPT",
	TagCHANGELOGTIME:      "CHANGELOGTIME",
	TagCHANGELOGNAME:      "CHANGELOGNAME",
	TagCHANGELOGTEXT:      "CHANGELOGTEXT",
	TagBROKENMD5:          "BROKENMD5",
	TagPREREQ:             "PREREQ",
	TagPREINPROG:          "PREINPROG",
	TagPOSTINPROG:         "POSTINPROG",
	TagPREUNPROG:          "PREUNPROG",
	TagPOSTUNPROG:         "POSTUNPROG",
	TagBUILDARCHS:         "BUILDARCHS",
	TagOBSOLETENAME:       "OBSOLETENAME",
	TagVERIFYSCRIPTPROG:   "VERIFYSCRIPTPROG",
	TagTRIGGERSCRIPTPROG:  "TRIGGERSCRIPTPROG",
	TagDOCDIR:             "DOCDIR",
	TagCOOKIE:             "COOKIE",
	TagFILEDEVICES:        "FILEDEVICES",
	TagFILEINODES:         "FILEINODES",
	TagFILELANGS:          "FILELANGS",
	TagPREFIXES:           "PREFIXES",
	TagINSTPREFIXES:       "INSTPREFIXES",
	TagTRIGGERIN:          "TRIGGERIN",
	TagTRIGGERUN:          "TRIGGERUN",
	TagTRIGGERPOSTUN:      "TRIGGERPOSTUN",
	TagAUTOREQ:            "AUTOREQ",
	TagAUTOPROV:           "AUTOPROV",
	TagCAPABILITY:         "CAPABILITY",
	TagSOURCEPACKAGE:      "SOURCEPACKAGE",
	TagOLDORIGFILENAMES:   "OLDORIGFILENAMES",
	TagBUILDPREREQ:        "BUILDPREREQ",
	TagBUILDREQUIRES:      "BUILDREQUIRES",
	TagBUILDCONFLICTS:     "BUILDCONFLICTS",
	TagBUILDMACROS:        "BUILDMACROS",
	TagPROVIDEFLAGS:       "PROVIDEFLAGS",
	TagPROVIDEVERSION:     "PROVIDEVERSION",
	TagOBSOLETEFLAGS:      "OBSOLETEFLAGS",
	TagOBSOLETEVERSION:    "OBSOLETEVERSION",
	TagDIRINDEXES:         "DIRINDEXES",
	TagBASENAMES:          "BASENAMES",
	TagDIRNAMES:           "DIRNAMES",
	TagORIGDIRINDEXES:     "ORIGDIRINDEXES",
	TagORIGBASENAMES:      "ORIGBASENAMES",
	TagORIGDIRNAMES:       "ORIGDIRNAMES",
	TagOPTFLAGS:           "OPTFLAGS",
	TagDISTURL:            "DISTURL",
	TagPAYLOADFORMAT:      "PAYLOADFORMAT",
	TagPAYLOADCOMPRESSOR:  "PAYLOADCOMPRESSOR",
	TagPAYLOADFLAGS:       "PAYLOADFLAGS",
	TagINSTALLCOLOR:       "INSTALLCOLOR",
	TagINSTALLTID:         "INSTALLTID",
	TagREMOVETID:          "REMOVETID",
	TagSHA1RHN:            "SHA",
	TagRHNPLATFORM:        "RHNPLATFORM",
	TagPLATFORM:           "PLATFORM",
	TagPATCHESNAME:        "PATCHESNAME",
	TagPATCHESFLAGS:       "PATCHESFLAGS",
	TagPATCHESVERSION:     "PATCHESVERSION",
	TagCACHECTIME:         "CACHECTIME",
	TagCACHEPKGPATH:       "CACHEPKGPATH",
	TagCACHEPKGSIZE:       "CACHEPKGSIZE",
	TagCACHEPKGMTIME:      "CACHEPKGMTIME",
	TagFILECOLORS:         "FILECOLORS",
	TagFILECLASS:          "FILECLASS",
	TagCLASSDICT:          "CLASSDICT",
	TagFILEDEPENDSX:       "FILEDEPENDSX",
	TagFILEDEPENDSN:       "FILEDEPENDSN",
	TagDEPENDSDICT:        "DEPENDSDICT",
	TagSOURCEPKGID:        "SOURCEPKGID",
	TagFILECONTEXTS:       "FILECONTEXTS",
	TagFSCONTEXTS:         "FSCONTEXTS",
	TagRECONTEXTS:         "RECONTEXTS",
	TagPOLICIES:           "POLICIES",
	TagPRETRANS:           "PRETRANS",
	TagPOSTTRANS:          "POSTTRANS",
	TagPRETRANSPROG:       "PRETRANSPROG",
	TagPOSTTRANSPROG:      "POSTTRANSPROG",
	TagDISTTAG:            "DIST",
	TagOLDSUGGESTSNAME:    "OLDSUGGESTSNAME",
	TagOLDSUGGESTSVERSION: "OLDSUGGESTSVERSION",
	TagOLDSUGGESTSFLAGS:   "OLDSUGGESTSFLAGS",
	TagOLDENHANCESNAME:    "OLDENHANCESNAME",
	TagOLDENHANCESVERSION: "OLDENHANCESVERSION",
	TagOLDENHANCESFLAGS:   "OLDENHANCESFLAGS",
	TagPRIORITY:           "PRIORITY",
	TagCVSID:              "CVSID",
	TagBLINKPKGID:         "BLINKPKGID",
	TagBLINKHDRID:         "BLINKHDRID",
	TagBLINKNEVRA:         "BLINKNEVRA",
	TagFLINKPKGID:         "FLINKPKGID",
	TagFLINKHDRID:         "FLINKHDRID",
	TagFLINKNEVRA:         "FLINKNEVRA",
	TagPACKAGEORIGIN:      "PACKAGEORIGIN",
	TagTRIGGERPREIN:       "TRIGGERPREIN",
	TagBUILDSUGGESTS:      "BUILDSUGGESTS",
	TagBUILDENHANCES:      "BUILDENHANCES",
	TagSCRIPTSTATES:       "SCRIPTSTATES",
	TagSCRIPTMETRICS:      "SCRIPTMETRICS",
	TagBUILDCPUCLOCK:      "BUILDCPUCLOCK",
	TagFILEDIGESTALGOS:    "FILEDIGESTALGOS",
	TagVARIANTS:           "VARIANTS",
	TagXMAJOR:             "XMAJOR",
	TagXMINOR:             "XMINOR",
	TagREPOTAG:            "REPO",
	TagKEYWORDS:           "KEYWORDS",
	TagBUILDPLATFORMS:     "BUILDPLATFORMS",
	TagPACKAGECOLOR:       "PACKAGECOLOR",
	TagPACKAGEPREFCOLOR:   "PACKAGEPREFCOLOR",
	TagXATTRSDICT:         "XATTRSDICT",
	TagFILEXATTRSX:        "FILEXATTRSX",
	TagDEPATTRSDICT:       "DEPATTRSDICT",
	TagCONFLICTATTRSX:     "CONFLICTATTRSX",
	TagOBSOLETEATTRSX:     "OBSOLETEATTRSX",
	TagPROVIDEATTRSX:      "PROVIDEATTRSX",
	TagREQUIREATTRSX:      "REQUIREATTRSX",
	TagBUILDPROVIDES:      "BUILDPROVIDES",
	TagBUILDOBSOLETES:     "BUILDOBSOLETES",
	TagDBINSTANCE:         "DBINSTANCE",
	TagNVRA:               "NVRA",
	TagFILENAMES:          "FILENAMES",
	TagFILEPROVIDE:        "FILEPROVIDE",
	TagFILEREQUIRE:        "FILEREQUIRE",
	TagFSNAMES:            "FSNAMES",
	TagFSSIZES:            "FSSIZES",
	TagTRIGGERCONDS:       "TRIGGERCONDS",
	TagTRIGGERTYPE:        "TRIGGERTYPE",
	TagORIGFILENAMES:      "ORIGFILENAMES",
	TagLONGFILESIZES:      "LONGFILESIZES",
	TagLONGSIZE:           "LONGSIZE",
	TagFILECAPS:           "FILECAPS",
	TagFILEDIGESTALGO:     "FILEDIGESTALGO",
	TagBUGURL:             "BUGURL",
	TagEVR:                "EVR",
	TagNVR:                "NVR",
	TagNEVR:               "NEVR",
	TagNEVRA:              "NEVRA",
	TagHEADERCOLOR:        "HEADERCOLOR",
	TagVERBOSE:            "VERBOSE",
	TagEPOCHNUM:           "EPOCHNUM",
	TagPREINFLAGS:         "PREINFLAGS",
	TagPOSTINFLAGS:        "POSTINFLAGS",
	TagPREUNFLAGS:         "PREUNFLAGS",
	TagPOSTUNFLAGS:        "POSTUNFLAGS",
	TagPRETRANSFLAGS:      "PRETRANSFLAGS",
	TagPOSTTRANSFLAGS:     "POSTTRANSFLAGS",
	TagVERIFYSCRIPTFLAGS:  "VERIFYSCRIPTFLAGS",
	TagTRIGGERSCRIPTFLAGS: "TRIGGERSCRIPTFLAGS",
	TagCOLLECTIONS:        "COLLECTIONS",
	TagPOLICYNAMES:        "POLICYNAMES",
	TagPOLICYTYPES:        "POLICYTYPES",
	TagPOLICYTYPESINDEXES: "POLICYTYPESINDEXES",
	TagPOLICYFLAGS:        "POLICYFLAGS",
	TagVCS:                "VCS",
	TagORDERNAME:          "ORDERNAME",
	TagORDERVERSION:       "ORDERVERSION",
	TagORDERFLAGS:         "ORDERFLAGS",
	TagMSSFMANIFEST:       "MSSFMANIFEST",
	TagMSSFDOMAIN:         "MSSFDOMAIN",
	TagINSTFILENAMES:      "INSTFILENAMES",
	TagREQUIRENEVRS:       "REQUIRENEVRS",
	TagPROVIDENEVRS:       "PROVIDENEVRS",
	TagOBSOLETENEVRS:      "OBSOLETENEVRS",
	TagCONFLICTNEVRS:      "CONFLICTNEVRS",
	TagFILENLINKS:         "FILENLINKS",
	TagRECOMMENDNAME:      "RECOMMENDNAME",
	TagRECOMMENDVERSION:   "RECOMMENDVERSION",
	TagRECOMMENDFLAGS:     "RECOMMENDFLAGS",
	TagSUGGESTNAME:        "SUGGESTNAME",
	TagSUGGESTVERSION:     "SUGGESTVERSION",
	TagSUGGESTFLAGS:       "SUGGESTFLAGS",
	TagSUPPLEMENTNAME:     "SUPPLEMENTNAME",
	TagSUPPLEMENTVERSION:  "SUPPLEMENTVERSION",
	TagSUPPLEMENTFLAGS:    "SUPPLEMENTFLAGS",
	TagENHANCENAME:        "ENHANCENAME",
	TagENHANCEVERSION:     "ENHANCEVERSION",
	TagENHANCEFLAGS:       "ENHANCEFLAGS",
	TagRECOMMENDNEVRS:     "RECOMMENDNEVRS",
	TagSUGGESTNEVRS:       "SUGGESTNEVRS",
	TagSUPPLEMENTNEVRS:    "SUPPLEMENTNEVRS",
	TagENHANCENEVRS:       "ENHANCENEVRS",
}
