.TH packit 1 "2018-12-13" "1.0.1
.
.SH NAME
packit \- packaging made easy

.SH SYNOPSIS
.SY packit
.OP \-d datadir
<packit.toml,...>
.YS
\" packit build sub command synopsis
.SY "packit build"
.OP \-d datadir
<packit.toml,...>
.YS
\" packit convert sub command synopsis
.SY "packit convert"
.OP -d datadir
<src.pkg>
<dst.pkg>
.YS
\" packit show sub command synopsis
.SY "packit show"
<package.pkg,...>
.YS
.
.SH DESCRIPTION
packit make it easy to package standalone binary with their configuration files,
their documentation, into common package format such as deb and rpm.

.SH OPTIONS
.TP
.BI \-d\  datadir
directory where packages will be written

.SH SEE ALSO
packit.toml(5), deb(5), rpm(8)
